"""PDF-verified Kedamono section labels and their existing zh-TW counterparts."""

HEADING_PAIRS: dict[str, tuple[tuple[str, str, int], ...]] = {
    'on-the-world/definition-of-a-kedamono.md': (
        ('Kedamono Are Behemoths', '暗獸是巨獸', 2),
        ('Kedamono Have No Lifespan', '暗獸沒有壽命', 2),
        ('Kedamono Prey on Humans', '暗獸以人類為食', 2),
        ('Kedamono Possess Lures', '暗獸擁有擬態誘餌', 2),
        ('Kedamono Understand Language', '暗獸理解語言', 2),
        ('Kedamono Abide Contracts', '暗獸遵守契約', 2),
        ('Kedamono Bring Disaster', '暗獸帶來災禍', 2),
        ('Humans Fascinate Them', '人類令牠們著迷', 2),
        ('Offspring', '子嗣', 2),
        ('Salvation', '救贖', 2),
    ),
    'on-the-world/the-dark-forest.md': (
        ('Location of the Forest', '森林的位置', 2),
        ('Forest Entrance', '森林入口', 2),
        ('Sprites', '精靈', 2),
        ('The Shadowsea', '影海', 2),
        ('Ouroboros River', '銜尾蛇河', 2),
        ('Primal Fog', '原初霧', 2),
        ('The Furthest Sea', '最遠之海', 2),
        ('The Dreamcatch Shore', '夢捕海岸', 2),
        ('Artifacts & Chantries', '聖物與小聖堂', 2),
        ('Walpurgis Mountain', '瓦爾普吉斯山', 2),
        ('The Template Kingdom', '鑄型王國', 2),
        ('Time and Place', '時代與地點', 2),
    ),
    'on-the-world/and-all-the-rest.md': (
        ('Faith', '信仰', 2),
        ('The Elves and the Dwarves', '精靈與矮人', 2),
        ('Monsters', '怪物', 2),
        ('Magick', '魔法', 2),
        ('Remnants of the Great Borean Empire', '波瑞亞大帝國的遺跡', 2),
        ('Orichalcum', '神鋁', 2),
    ),
    'on-kedamono/kedamono-species/index.md': (
        ('Using Your Opera', '使用歌劇', 3),
        ('Legend Upon Legend', '傳說不只一則', 3),
    ),
    'on-kedamono/kedamono-species/arachne.md': (
        ('Skyblend Crystalwire', '融於空氣的水晶絲', 2),
        ('Arachne Lures', '阿拉克涅的擬態誘餌', 2),
        ('Children of Arachne', '阿拉克涅的子嗣', 2),
    ),
    'on-kedamono/kedamono-species/dreadhare.md': (
        ('Horns, Teeth, and Madness', '角、牙與瘋狂', 2),
        ('Red Eyes of Fortune', '紅眼與幸運', 2),
        ('Dreadhare Lures', '恐懼兔的擬態誘餌', 2),
    ),
    'on-kedamono/kedamono-species/goliath.md': (
        ('Nimble Fingers', '靈巧的手指（Feat）', 2),
        ('The First Artists', '最初的藝術家', 2),
        ('Goliath Lures', '歌利亞的擬態誘餌（Lure）', 2),
        ('Controlling Beats', '操控節拍', 2),
    ),
    'on-kedamono/kedamono-species/sphinx.md': (
        ('Fickle Beasts', '善變的野獸', 2),
        ('Body Composition', '身體構造', 2),
        ('Riddles of the Sphinx', '斯芬克斯的謎題', 2),
    ),
    'on-kedamono/kedamono-species/dragon.md': (
        ('Fiends of Hell', '地獄的惡魔', 2),
        ('Fire & Poison', '火焰與毒', 2),
        ('Dragon Lures', '龍族的擬態誘餌', 2),
        ('Vengeance Upon the Lord', '向光之主復仇', 2),
        ('Dragonettes', '幼龍', 2),
        ('A Dream That Grants Wishes', '實現願望的夢', 2),
    ),
    'on-kedamono/kedamono-species/mandrosa.md': (
        ('Briars and Trap Leaves', '荊棘藤與捕食葉', 2),
        ('Mandrosa Lures', '曼德羅薩的擬態誘餌', 2),
        ('First Love, Again', '再一次的初戀', 2),
        ('Pure Nectar', '純淨花蜜', 2),
        ('Our Little Flower', '我們的小花', 2),
    ),
    'on-kedamono/kedamono-species/mimirstrix.md': (
        ('Mimirstrix Lures', '米米爾斯特里克斯的擬態誘餌', 2),
    ),
    'on-kedamono/kedamono-species/merkaba.md': (
        ('Conceptual Hearts & Becoming Kedamono', '哲學心臟與成為暗獸', 2),
        ('Merkaba Lures', '梅爾卡巴的擬態誘餌', 2),
        ('A New Pilot', '新駕駛員', 2),
    ),
    'on-kedamono/kedamono-species/shadewolf.md': (
        ('Nightstalkers', '夜行者', 2),
        ('Shadewolf Lures', '闇狼的擬態誘餌', 2),
        ('Eating the Moon', '噬月', 2),
    ),
    'on-kedamono/kedamono-species/rahab.md': (
        ('Deep-Sea Artifacts', '深海遺物', 2),
        ('Infinite Evolution', '無限進化', 2),
        ('Devils of Love', '愛的惡魔', 2),
    ),
    'on-kedamono/making-a-kedamono.md': (
        ('Guidance', '指引', 2),
    ),
    'session-rules/playing-with-friends.md': (
        ('Playing a Kedamono', '扮演暗獸', 3),
        ('Deciding Fates', '決定命運', 3),
        ('Be Cooperative', '互相合作', 3),
        ('Be Ready for Tragedy', '做好面對悲劇的準備', 3),
        ('Safeguard Your Kedamono', '守護自己的暗獸', 3),
    ),
    'session-rules/prelude.md': (
        ('Necessary Items', '必要物品', 2),
        ('The Who, Where & When', '約定時間與地點', 3),
        ('Decide Who GMs', '決定主持人', 3),
        ('Select a Scenario', '選擇劇本', 3),
        ('Unveil the Intro', '公開前奏情報', 3),
        ('Select Participating Kedamono', '選擇參加的暗獸', 3),
        ('Helpful Kedamono', '暗獸為何助人', 3),
        ('Kedamono Introductions', '介紹暗獸', 3),
        ('Mark Intro Portents', '標記前奏預言', 3),
        ('Kedamono Identity', '暗獸的身分', 3),
        ('Decide Initiative', '決定行動順序', 3),
        ('Determine Pack', '決定夥群（Pack）', 3),
    ),
    'session-rules/on-stage-and-curtain-call.md': (
        ('Conversation', '對話', 3),
        ('Progression through Discussion', '透過討論推進故事', 3),
        ('Quitting the Story', '退出故事', 3),
        ('The Final Say is the GM’s', '最終決定權在主持人手上', 3),
        ('Special Actions', '特殊行動', 3),
        ('Taking Breaks', '休息時間', 3),
        ('Interludes', '- 間奏（Interlude）', 3),
        ('Invisibility Magick', '隱形魔法', 3),
        ('Bringing the Stage to a Close', '結束舞台演出', 3),
        ('Cruel Endings', '殘酷的結局', 3),
        ('Aftermath', '後日談', 3),
        ('Kedamono Reset', '重置暗獸', 3),
        ('Gain a New Legend', '獲得新的傳說', 3),
    ),
    'session-rules/portents.md': (
        ('Player’s Choice', '玩家來選擇', 3),
        ('Wording of a Portent', '預言的措辭', 3),
        ('The “When” of Fulfilling', '實現預言的「時間」', 3),
        ('Fulfillment by Others', '由他人實現', 3),
        ('Overturning Portents', '推翻預言', 3),
        ('Portents of Death', '死亡預言', 3),
        ('Remarking the Same Portent', '再次標記同一則預言', 3),
        ('Portent Contradictions', '預言互相矛盾', 3),
        ('Clearing Intro Portents', '清除前奏預言', 3),
    ),
    'session-rules/ordeals.md': (
        ('Using Feats', '使用特技', 3),
        ('Triumph', '達成（Triumph）', 3),
        ('Gaining Agonies', '獲得苦難點', 3),
        ('Promise of Victory', '勝利必成', 3),
        ('Vital Info', '關鍵資訊', 3),
        ('Shared Portents', '共用預言', 3),
        ('Switching Ordeals', '切換試煉', 3),
        ('Path of Glory', '榮光之門', 3),
        ('Path of Agony', '苦難之門', 3),
        ('Match Conditions', '勝負條件', 3),
        ('Gaining Agonies', '獲得苦難點', 3),
        ('Victor & the Defeated', '勝者與敗者', 3),
    ),
    'session-rules/taboos-options-and-diceless.md': (
        ('The Forbidden', '禁止之事', 3),
        ('Handling Taboos', '如何處理禁忌', 3),
        ('An Angel Appears', '天使現身', 3),
        ('Using a Woespeaker', '使用災厄天使', 3),
        ('No Rolling', '不擲骰', 3),
        ('Checks', '判定', 3),
    ),
    'on-game-mastering/gm-guidance.md': (
        ('Running the Stage', '帶領舞台演出（On Stage）', 2),
        ('Questions from Players', '玩家提問', 3),
        ('Fulfilling Portents', '實現預言', 3),
        ('Portraying NPCs', '扮演登場人物', 3),
        ("GM's Approval", '主持人的核准', 3),
        ("When It's Not in the Scenario", '劇本未提及的情況', 3),
        ('Skip Ordeals', '略過試煉', 3),
        ('Abstract Ordeals', '抽象化試煉', 3),
        ('Give It Its Ending', '讓故事落幕', 3),
    ),
}
