#!/usr/bin/env python3
"""Generate the redirect an old GitHub Pages book site serves after blog migration.

Writes a static redirect site plus a Pages workflow into the book repo. Pages cannot
send a 301, so every old page gets a meta refresh, a canonical link, and a script that
keeps the query and fragment; 404.html forwards any other path.
"""

from __future__ import annotations

import argparse
import html
import json
import re
import sys
from pathlib import Path

BLOG_BOOKS_URL = "https://www.wayneh.tw/books"
PAGES_SITE_DIR = "old-host-redirect"

PAGES_WORKFLOW = f"""name: Deploy to GitHub Pages

# The book moved to the blog. This publishes the redirect site generated by the
# template's tools/old_host_redirect.py; regenerate it with that tool.

on:
  push:
    branches: [main]
    paths: ['{PAGES_SITE_DIR}/**', '.github/workflows/deploy.yml']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{{{ steps.deployment.outputs.page_url }}}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: {PAGES_SITE_DIR}
      - id: deployment
        uses: actions/deploy-pages@v4
"""


def target_base(slug: str, blog_books_url: str) -> str:
    if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", slug):
        raise ValueError("slug must use lowercase letters, digits, and hyphens")
    return f"{blog_books_url.rstrip('/')}/{slug}"


def redirect_page(url: str, script: str) -> str:
    escaped = html.escape(url, quote=True)
    return (
        '<!doctype html><html lang="zh-TW"><head><meta charset="utf-8">'
        f'<title>已搬家</title><link rel="canonical" href="{escaped}">'
        f'<meta name="robots" content="noindex"><meta http-equiv="refresh" content="0; url={escaped}">'
        f"<script>{script}</script></head>"
        f'<body><p>本站已搬到 <a href="{escaped}">{escaped}</a>。</p></body></html>\n'
    )


def write_github_pages(repo: Path, target: str, pages_from: Path, old_base: str) -> list[str]:
    if not pages_from.is_dir():
        raise ValueError(f"page source directory not found: {pages_from}")
    pages = sorted(path.relative_to(pages_from).as_posix() for path in pages_from.rglob("*.html"))
    pages = [rel for rel in pages if rel != "404.html"]
    if not pages:
        raise ValueError(f"page source has no HTML pages: {pages_from}")
    site = repo / PAGES_SITE_DIR
    written = []
    for rel in pages:
        path = rel[: -len("index.html")] if rel.endswith("index.html") else rel
        url = f"{target}/{path}"
        dest = site / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(redirect_page(url, f"location.replace({json.dumps(url)}+location.search+location.hash)"), encoding="utf-8")
        written.append(f"{PAGES_SITE_DIR}/{rel}")
    old_base = "/" + old_base.strip("/") if old_base.strip("/") else ""
    fallback = (
        f"var b={json.dumps(old_base)},p=location.pathname;"
        "if(b&&(p===b||p.indexOf(b+'/')===0))p=p.slice(b.length);"
        f"location.replace({json.dumps(target)}+(p||'/')+location.search+location.hash)"
    )
    (site / "404.html").write_text(redirect_page(f"{target}/", fallback), encoding="utf-8")
    (site / ".nojekyll").write_text("", encoding="utf-8")
    workflow = repo / ".github/workflows/deploy.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(PAGES_WORKFLOW, encoding="utf-8")
    return written + [f"{PAGES_SITE_DIR}/404.html", f"{PAGES_SITE_DIR}/.nojekyll", ".github/workflows/deploy.yml"]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--blog-books-url", default=BLOG_BOOKS_URL, help=f"Blog URL that holds the books (default {BLOG_BOOKS_URL})")
    hosts = parser.add_subparsers(dest="host", required=True)
    pages = hosts.add_parser("github-pages", help="Meta-refresh redirect site and workflow for a book repo")
    pages.add_argument("--slug", required=True, help="Blog slug of the book")
    pages.add_argument("--repo", type=Path, required=True, help="Book checkout that publishes GitHub Pages")
    pages.add_argument("--pages-from", type=Path, required=True, help="Build or export directory whose HTML pages list the old paths")
    pages.add_argument("--old-base", default="", help="Path prefix of the old Pages site, such as /cairn-barebones-docs")
    args = parser.parse_args()
    try:
        target = target_base(args.slug, args.blog_books_url)
        written = write_github_pages(args.repo, target, args.pages_from, args.old_base)
        root = args.repo
    except (ValueError, OSError) as exc:
        print(f"Redirect error: {exc}", file=sys.stderr)
        return 1
    print(json.dumps({"host": args.host, "target": f"{target}/", "root": str(root.resolve()), "files": len(written)}, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
